# Makefile para ejecutar los scripts serv3.py y cliente3.py

file = $@
# Objetivo predeterminado
all: serv3.py cli3.py

# Objetivo para ejecutar el script serv3.py
serv3.py:
	python3 serv3.py
# Objetivo para ejecutar el script cliente3.py
cli3.py:
	python3 cli3.py $(file)
