all: serv cli

serv:
	@echo "Compilando y ejecutando el servidor..."
	@python3 serv7.py

cli:
	@echo "Compilando y ejecutando el cliente..."
	@python3 cli7.py

clean:
	@echo "Limpiando archivos temporales y resultados de la compilación..."
