

all: serv cli

serv:
	@echo "Compilando y ejecutando el servidor..."
	@python3 serv6.py

cli:
	@echo "Compilando y ejecutando el cliente..."
	@python3 cli6.py

clean:
	@echo "Limpiando archivos temporales y resultados de la compilación..."
	# Agrega aquí los comandos de limpieza, si es necesario
