

all: serv cli

serv:
	@echo "Compilando y ejecutando el servidor..."
	@python3 serv5.py

cli:
	@echo "Compilando y ejecutando el cliente..."
	@python3 cli5.py $(file)

clean:
	@echo "Limpiando..."
	# Agrega aquí los comandos de limpieza, si es necesario
