all:
	@echo "Ejecutando con fichero: "
	python3 serv.py & cli.py prueba.txt

binary:
	@echo "Ejecutando con fichero /bin/sh"
	python3 serv.py & cli.py /bin/sh

services:
	@echo "Ejecutando con fichero /etc/services"
	python3 serv.py & cli.py /etc/services

clean:
	@echo "Limpiando..."